### PR TITLE
Fixing ogp meta data for all pages

### LINKED ISSUE #88: Implement OpenGraph protocol across the site
Reference:
* http://ogp.me/
* https://nuxtjs.org/api/pages-head/

Start with basic metadata:
- [x] og:title - The title of your object as it should appear within the graph, e.g., "The Rock".
- [x]  og:type - The type of your object, e.g., "video.movie". Depending on the type you specify, other properties may also be required.
- [x]  og:image - An image URL which should represent your object within the graph.
- [x]  og:url - The canonical URL of your object that will be used as its permanent ID in the graph, e.g., "http://www.imdb.com/title/tt0117500/".
- [ ] og:description - A one to two sentence description of your object.
- [ ] og:site_name - If your object is part of a larger web site, the name which should be displayed for the overall site. e.g., "IMDb"

### PR DESCRIPTION
**Pull request by KriAga**
Fixes: https://github.com/factly/dega-web/issues/88

### CODE REVIEW

File: layouts/default.vue [hunk 1]
```diff
@@ -123,22 +123,24 @@ export default {
...
         { rel: 'icon', type: 'image/x-icon', href: this.organisation.fav_icon_url },
       ],
       meta: [
-        { hid: 'og:image', name: 'og:image', content: this.prodBaseUrl + DefaultImage },
+        { name: 'google-site-verification', content: this.organisation.google_verification_code},
+        { hid: 'og:title', name: 'og:title', content: this.organisation.name },
+        { hid: 'og:url', name: 'og:url', content:  this.organisation.site_address + this.$nuxt.$route.path},
+        { hid: 'og:image', name: 'og:image', content: this.organisation.site_address + DefaultImage },
         { hid: 'og:description', name: 'og:description', content: this.organisation.description},
-        { name: 'google-site-verification', content: this.organisation.google_verification_code}
```
Comment (deshetti) [inline layouts/default.vue]: Add the following: 

og:site_name - If your object is part of a larger web site, the name which should be displayed for the overall site. e.g., "IMDb". This will be organisation.name

File: pages/author/_slug/index.vue [hunk 2]
```diff
@@ -77,7 +77,6 @@ export default {
       title: this.story[0].authors[0].display_name,
       meta: [
         { hid: 'og:title', name: 'og:title', content: this.story[0].authors[0].display_name },
-        // { hid: 'og:url', name: 'og:url', content:  process.env.domainHostname + $nuxt.$route.name},
```
Comment (deshetti) [inline pages/author/_slug/index.vue:73]: Add the following: 

Populate og:description if authors[0].description is not null. Otherwise og:description from default.vue will take over.

File: pages/category/_slug/index.vue [hunk 3]
```diff
@@ -76,7 +76,6 @@ export default {
       title: this.story[0].categories[0].name,
       meta: [
         { hid: 'og:title', name: 'og:title', content: this.story[0].categories[0].name },
-        // { hid: 'og:url', name: 'og:url', content:  process.env.domainHostname + $nuxt.$route.name},
```
Comment (deshetti) [inline pages/category/_slug/index.vue:74]: Add the following:

Populate og:description if story[0].categories[0].description. Otherwise og:description from default.vue will take over.

File: pages/factcheck/_slug/index.vue [hunk 4]
```diff
@@ -99,7 +99,6 @@ export default {
       title: this.factcheck[0].title,
       meta: [
         { hid: 'og:title', name: 'og:title', content: this.factcheck[0].title },
-        // { hid: 'og:url', name: 'og:url', content:  process.env.domainHostname + $nuxt.$route.name},
```
Comment (deshetti) [inline pages/factcheck/_slug/index.vue:100]: Add the following:

Populate og:description if factcheck[0].excerpt. Otherwise og:description from default.vue will take over.

File: pages/post/_slug/index.vue [hunk 5]
```diff
@@ -67,7 +67,6 @@ export default {
       title: this.post[0].title,
       meta: [
         { hid: 'og:title', name: 'og:title', content: this.post[0].title },
-        // { hid: 'og:url', name: 'og:url', content:  process.env.domainHostname + $nuxt.$route.name},
```
Comment (deshetti) [inline pages/post/_slug/index.vue:68]: Populate og:description if post[0].excerpt. Otherwise og:description from default.vue will take over.

File: pages/tag/_slug/index.vue [hunk 6]
```diff
@@ -78,7 +78,6 @@ export default {
       title: this.story[0].tags[0].name,
       meta: [
         { hid: 'og:title', name: 'og:title', content: this.story[0].tags[0].name },
-        // { hid: 'og:url', name: 'og:url', content:  process.env.domainHostname + $nuxt.$route.name},
```
Comment (deshetti) [inline pages/tag/_slug/index.vue:74]: Populate og:description if story[0]tags[0].description. Otherwise og:description from default.vue will take over.

**Review by deshetti — APPROVED** [review]
